data:
  root_dir: "./data/WHU"  # 数据集根目录
  input_size: 1024    # 输入尺寸
  num_workers: 5      # 数据加载工作线程数

dataset:
  num_classes: 2
  class_names: ['背景', '建筑']
  binary_mode: true  # 可选，默认情况下num_classes=2时自动启用

model:
  # SAM配置
  sam_type: "vit_h"  # 选项: vit_b, vit_l, vit_h
  checkpoint: "sam_vit_h_4b8939.pth"
  freeze_image_encoder: true
  # max_queries_per_batch: 15    # 每批处理的最大查询数
  # per_query_mask: False
  max_foreground_queries: 10
  memory_efficient: true  # 使用内存优化模式
  
  # 特征聚合器配置
  feature_layers: [0, 8, 16, 24, 31]  # 每隔4层选择一个ViT层
  out_channels: 32  # 输出通道数
  
  # 查询提示器配置
  num_points_per_query: 5  # 每个查询的提示点数量
  num_encoder_layers: 3
  num_decoder_layers: 6
  num_queries: 15  # 对象查询数量
  hidden_dim: 256
  dropout: 0.1
  
  # 梯度模块配置
  use_gradient: true
  
  # 掩码编码器配置
  use_coarse_mask: true

training:
  batch_size: 2
  lr: 0.0001
  weight_decay: 0.0001
  epochs: 300
  lr_drop: 200
  gradient_accumulation_steps: 4
  
  # 损失权重
  loss_weights:
    class_loss_coef: 5.0
    mask_loss_coef: 5.0
    dice_loss_coef: 5.0
    prompt_loss_coef: 1.0

  ddp_optimization:
    master_weights_only: true  # 仅在主进程保存模型权重
    broadcast_buffers: false   # 禁用缓冲区广播以提高性能

distributed:
  sync_bn: true             # 是否使用同步批量归一化
  find_unused_parameters: true  # 是否查找未使用的参数(用于复杂模型)
  gradient_as_bucket_view: true # 优化内存使用
  backend: 'nccl'           # 分布式通信后端，NVIDIA GPU推荐使用nccl


